---
name: Unit and integration tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-itwinai:
    name: Test itwinai with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install plugin dependencies
        shell: bash -l {0}
        run: |
          python -m venv .venv &&
          source .venv/bin/activate &&
          pip install uv &&
          uv pip install .

      - name: Run tests with pytest
        shell: bash -l {0}
        run: .venv/bin/pytest -v tests/
