name: Testing Hython itwinai plugin with pytest

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  test-itwinai-plugin:
    name: Testing itwinai plugin with pytest
    runs-on: ubuntu-latest
    steps:

      # Uncomment this only if you run out of disk space!
      # - name: Maximize Disk Space
      #   uses: easimon/maximize-build-space@v10
      #   with:
      #     # Reserve space on root for docker/dagger cache
      #     build-mount-path: /docker
      #     root-reserve-mb: 2048
      #     overprovision-lvm: false
      #     swap-size-mb: 4096
      #     remove-dotnet: true
      #     remove-android: true
      #     remove-haskell: true
      #     remove-codeql: true

      - uses: actions/checkout@v5
      
      #  ALSO uncomment this only if you run out of disk space!
      # - name: Move Docker directory
      #   shell: bash
      #   run: |
      #     sudo mv /var/lib/docker /docker/ &&
      #     sudo ln -s /docker/docker /var/lib/docker &&
      #     sudo systemctl restart docker

      # Run tests with pytest in a container
      - name: Run Integration Test (development pipeline)
        uses: dagger/dagger-for-github@v7
        with:
          workdir: ci
          verb: call
          module: itwinai
          args: >-
            build-container
            --context ..
            --dockerfile ../env-files/Dockerfile
            test-local
            --cmd "pytest,-v,--disable-warnings,-n,logical,/app/tests/,--dist,loadfile"
            logs
          # Add a Dagger Cloud token here to have the logs stored also on Dagger Cloud
          # cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: latest